{% set version = "22.2.0" %}
{% set sha256 = "fdd4576dc9d25e0a14b200236f9e7d5b564a6cc671ae45c7127242091fd22d7b" %}

package:
  name: structlog
  version: {{ version }}

source:
  fn: structlog-{{ version }}.tar.gz
  url: https://github.com/hynek/structlog/archive/{{ version }}.zip
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
    - flit

  run:
    - python >=3.7

test:
  imports:
    - structlog

about:
  home: http://www.structlog.org
  license: Apache-2.0 OR MIT
  summary: Structured Logging for Python
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE

extra:
  recipe-maintainers:
    - vamega
    - aldanor
