{% set name = "structlog" %}
{% set version = "25.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/structlog-{{ version }}.tar.gz
  sha256: 186cd1b0a8ae762e29417095664adf1d6a31702160a46dacb7796ea82f7409e4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
    - hatch-fancy-pypi-readme >=22.8.0

  run:
    - python >={{ python_min }}
    - typing-extensions

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - structlog
  commands:
    - pip check

about:
  home: http://www.structlog.org
  license: Apache-2.0 OR MIT
  summary: Structured Logging for Python
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
  dev_url: https://github.com/hynek/structlog

extra:
  recipe-maintainers:
    - vamega
    - aldanor
    - synapticarbors
