{% set version = "24.4.0" %}
{% set sha256 = "bd10527942dae90e8c44f0e1a170062b3a1787e1139a633508da5eb1ca426cd1" %}

package:
  name: structlog
  version: {{ version }}

source:
  fn: structlog-{{ version }}.tar.gz
  url: https://github.com/hynek/structlog/archive/{{ version }}.zip
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
    - hatch-fancy-pypi-readme

  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - structlog

about:
  home: http://www.structlog.org
  license: Apache-2.0 OR MIT
  summary: Structured Logging for Python
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE

extra:
  recipe-maintainers:
    - vamega
    - aldanor
