{% set version = "22.3.0" %}
{% set sha256 = "e58c969f64dde50bfc02269e6bd024499363f239363ae9f2e691620ceb9df1dd" %}

package:
  name: structlog
  version: {{ version }}

source:
  fn: structlog-{{ version }}.tar.gz
  url: https://github.com/hynek/structlog/archive/{{ version }}.zip
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
    - flit
    - hatchling

  run:
    - python >=3.7

test:
  imports:
    - structlog

about:
  home: http://www.structlog.org
  license: Apache-2.0 OR MIT
  summary: Structured Logging for Python
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE

extra:
  recipe-maintainers:
    - vamega
    - aldanor
