schema_version: 1

context:
  name: structlog
  version: 25.5.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/structlog-${{ version }}.tar.gz
  sha256: 098522a3bebed9153d4570c6d0288abf80a031dfdb2048d59a49e9dc2190fc98

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-vcs
    - hatch-fancy-pypi-readme >=22.8.0
  run:
    - python >=${{ python_min }}
    - typing-extensions

tests:
  - python:
      imports:
        - structlog
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0 OR MIT
  summary: Structured Logging for Python
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
  homepage: http://www.structlog.org
  repository: https://github.com/hynek/structlog

extra:
  recipe-maintainers:
    - vamega
    - aldanor
    - synapticarbors
